# Generated by Django 5.2.5 on 2025-08-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=225, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Image should be 588 x 137 pixels or will get resized on upload', null=True, upload_to='site-logo/')),
                ('favicon', models.ImageField(blank=True, help_text='Image should be 128 x 128 pixels or will get resized on upload', null=True, upload_to='site-favicon/')),
                ('facebook_link', models.URLField(blank=True, help_text='Link to the Facebook page', null=True)),
                ('twitter_link', models.URLField(blank=True, help_text='Link to the Twitter profile', null=True)),
                ('instagram_link', models.URLField(blank=True, help_text='Link to the Instagram profile', null=True)),
                ('tiktok_link', models.URLField(blank=True, help_text='Link to the Tiktok profile', null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address of the site', null=True)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address for inquiries', max_length=254, null=True)),
                ('contact_number', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
        ),
    ]
