# Generated by Django 5.2.5 on 2025-08-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='The content of the flash message')),
                ('published', models.BooleanField(default=False, help_text='Indicates whether the flash message is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the flash message was created')),
            ],
            options={
                'verbose_name': 'Flash Message',
                'verbose_name_plural': 'Flash Messages',
            },
        ),
    ]
