# Generated by Django 5.2.5 on 2025-08-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_flashmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashmessage',
            name='highlighted_text',
            field=models.CharField(blank=True, help_text='Text to highlight in the flash message', max_length=255, null=True),
        ),
    ]
