# Generated by Django 5.0.6 on 2025-08-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_flashmessage_highlighted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
