# Generated by Django 5.2.5 on 2025-08-07 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caramenity',
            options={'verbose_name': 'Car Amenity', 'verbose_name_plural': 'Car Amenities'},
        ),
    ]
