# Generated by Django 5.0.6 on 2025-08-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_alter_caramenity_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.PositiveIntegerField(default=0, help_text='Average user rating for the car, typically from 1 to 5 stars.'),
        ),
    ]
