# Generated by Django 5.0.6 on 2025-08-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0003_car_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rating',
            field=models.FloatField(default=0, help_text='Average user rating for the car, typically from 1 to 5 stars.'),
        ),
    ]
