# Generated by Django 5.0.6 on 2025-08-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_alter_car_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.CharField(help_text='The car’s engine power measured in horsepower.', max_length=30),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(default='automatic', help_text='Type of transmission system (e.g., Automatic, Manual).', max_length=50),
        ),
    ]
