# Generated by Django 5.0.6 on 2025-08-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0005_alter_car_horsepower_alter_car_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gasoline', 'Gasoline'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', help_text='Type of fuel the car uses (Petrol, Diesel, Electric, etc.).', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='horsepower',
            field=models.CharField(help_text='The car’s engine power measured in horsepower.', max_length=50),
        ),
    ]
