# Generated by Django 5.0.6 on 2025-08-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0006_alter_car_fuel_type_alter_car_horsepower'),
    ]

    operations = [
        migrations.AddField(
            model_name='caramenity',
            name='is_search_filter_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Bugatti', 'Bugatti'), ('Cadillac', 'Cadillac'), ('Ferrari', 'Ferrari'), ('Genesis', 'Genesis'), ('Infiniti', 'Infiniti'), ('Jaguar', 'Jaguar'), ('Koenigsegg', 'Koenigsegg'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lincoln', 'Lincoln'), ('Lotus', 'Lotus'), ('Lucid', 'Lucid'), ('Maserati', 'Maserati'), ('Maybach', 'Maybach'), ('McLaren', 'McLaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Pagani', 'Pagani'), ('Porsche', 'Porsche'), ('Rolls-Royce', 'Rolls-Royce'), ('Range Rover', 'Range Rover'), ('Tesla', 'Tesla')], help_text='The brand or manufacturer of the car (e.g., Mercedes, BMW).', max_length=50),
        ),
    ]
