# Generated by Django 5.0.6 on 2025-08-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0007_caramenity_is_search_filter_enabled_alter_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(blank=True, help_text='Main image of the car used in listings.', null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.FileField(help_text='An additional image for this car.', upload_to='car_images/'),
        ),
    ]
