# Generated by Django 4.1.4 on 2025-08-26 18:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0008_alter_car_image_alter_carimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text="User's profile image", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=cloudinary.models.CloudinaryField(help_text='An additional image for this car.', max_length=255),
        ),
    ]
